export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const GET_ALL_PROFILE = 'GET_ALL_PROFILE';
export const GET_DEVELOPER_PROFILE = 'GET_DEVELOPER_PROFILE';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const SUBMIT_POST = 'SUBMIT_POST';
export const POST_LOADING = 'POST_LOADING';
export const GET_COMMENTS = 'GET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';


export const FETCH_USER_LOGIN_SUCCESS = 'FETCH_USER_LOGIN_SUCCESS'
export const FETCH_USER_LOGIN_REQUEST = 'FETCH_USER_LOGIN_REQUEST'
export const FETCH_USER_LOGIN_ERROR = 'FETCH_USER_LOGIN_ERROR'

export const FETCH_ALL_DEVELOPERS_REQUEST = 'FETCH_ALL_DEVELOPERS_REQUEST'
export const FETCH_ALL_DEVELOPERS_SUCCESS = 'FETCH_ALL_DEVELOPERS_SUCCESS'
export const FETCH_ALL_DEVELOPERS_ERROR = 'FETCH_ALL_DEVELOPERS_ERROR'

export const FETCH_PROFILE_REQUEST = 'FETCH_DEVELOPER_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_DEVELOPER_PROFILE_SUCCESS'
export const FETCH_PROFILE_ERROR = 'FETCH_DEVELOPER_PROFILE_ERROR'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

	 
